version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: product-service
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_TOOR_USERNAME=user
      - MONGO)INITDB_ROOT_PASSWORD=pass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERBER=mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network